### ISSUE TITLE
BGM再生中にPause/Resumeを繰り返すと途中でBGMが終了してしまう

### ISSUE THREAD

**Issue by bx-KazukiMurakami** [CyberAgentGameEntertainment/AudioConductor#7]
お世話になっております。
本パッケージを使用させていただいているのですが、1つバグを発見いたしましたのでご共有いたします。

動作環境
・Windows 11
・Unity 2022.3.36f1
・Audio Conductor ver1.0.0

現象内容
・任意のループしないBGMを再生開始後、TrackController.Pause()とTrackController.Resume()を連続で呼び出すとBGMが途中で終了してしまいます。

現象の確認方法
１．PackageManagerからAudioConductorをProjectに追加する
２．Sampleもダウンロードする
３．Assets/Sample/AudioConductor/1.0.0/Sample/Sample.unity シーンを開く
４．エディタのプレイボタンを押す
５．画面内に「Play Cue」というボタンがあるので押す（BGMが再生される）
６．BGMが再生されたら、同じく画面内の「Pause / Resume」というボタンを連打する
７．ある程度連打したらResumeした所でBGMをそのまま聴く
８．本来BGMが最後まで行ったら再生終了となるが、途中で再生が終了してしまうことを確認する

もし修正の目途が立ちそうであれば修正の方をお願いできればと思います。
よろしくお願いします。

**Comment by hkmt-mmy** [comment]
@bx-KazukiMurakami 
ご報告ありがとうございます。
こちらいただいた通りの現象が確認できましたので、修正を進めます。
